glib-2.0: Ignore useless warning found with gcc-6
Backport of:
commit 3fdecff96dd7516605ec9248b2a39de4db81306f
Author: Khem Raj <raj.khem@gmail.com>
Date:   Wed May 11 10:35:06 2016 -0700

    glib-2.0: Ignore useless warning found with gcc-6

    ../../glib-2.46.2/glib/gdate.c:2497:7: error: format not a string literal, format string not checked [-Werror=format-nonliteral]
           tmplen = strftime (tmpbuf, tmpbufsize, locale_format, &tm);
           ^~~~~~

    | ../../../../../../../../workspace/sources/glib-2.0/glib/tests/gdatetime.c: In function 'test_strftime':
    | ../../../../../../../../workspace/sources/glib-2.0/glib/tests/gdatetime.c:1338:3: error: '%c' yields only last 2 digits of year in some locales [-Werror=format-y2k]
    |    "a%a A%A b%b B%B c%c C%C d%d e%e F%F g%g G%G h%h H%H I%I j%j m%m M%M " \

    Additionally fix the problem seen where write() return code is ignored

    Signed-off-by: Khem Raj <raj.khem@gmail.com>
    Signed-off-by: Richard Purdie <richard.purdie@linuxfoundation.org>

Signed-off-by: Andreas Müller <schnitzeltony@googlemail.com>